# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param synth.incrementalSynthesisCache /tmp/.Xil_krushna_dev/Vivado-3087-VLSIdevbox/incrSyn
  set_param chipscope.maxJobs 1
  create_project -in_memory -part xc7a35tcpg236-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir {/home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/i2c_v2019.cache/wt} [current_project]
  set_property parent.project_path {/home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/i2c_v2019.xpr} [current_project]
  set_property ip_output_repo {{/home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/i2c_v2019.cache/ip}} [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet {{/home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/i2c_v2019.runs/synth_1/I2C.dcp}}
  read_xdc {{/home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/i2c_v2019.srcs/constrs_1/new/constraints.xdc}}
  link_design -top I2C -part xc7a35tcpg236-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force I2C_opt.dcp
  create_report "impl_2_opt_report_drc_0" "report_drc -file I2C_drc_opted.rpt -pb I2C_drc_opted.pb -rpx I2C_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force I2C_placed.dcp
  create_report "impl_2_place_report_io_0" "report_io -file I2C_io_placed.rpt"
  create_report "impl_2_place_report_utilization_0" "report_utilization -file I2C_utilization_placed.rpt -pb I2C_utilization_placed.pb"
  create_report "impl_2_place_report_control_sets_0" "report_control_sets -verbose -file I2C_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force I2C_routed.dcp
  create_report "impl_2_route_report_drc_0" "report_drc -file I2C_drc_routed.rpt -pb I2C_drc_routed.pb -rpx I2C_drc_routed.rpx"
  create_report "impl_2_route_report_methodology_0" "report_methodology -file I2C_methodology_drc_routed.rpt -pb I2C_methodology_drc_routed.pb -rpx I2C_methodology_drc_routed.rpx"
  create_report "impl_2_route_report_power_0" "report_power -file I2C_power_routed.rpt -pb I2C_power_summary_routed.pb -rpx I2C_power_routed.rpx"
  create_report "impl_2_route_report_route_status_0" "report_route_status -file I2C_route_status.rpt -pb I2C_route_status.pb"
  create_report "impl_2_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file I2C_timing_summary_routed.rpt -pb I2C_timing_summary_routed.pb -rpx I2C_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_2_route_report_incremental_reuse_0" "report_incremental_reuse -file I2C_incremental_reuse_routed.rpt"
  create_report "impl_2_route_report_clock_utilization_0" "report_clock_utilization -file I2C_clock_utilization_routed.rpt"
  create_report "impl_2_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file I2C_bus_skew_routed.rpt -pb I2C_bus_skew_routed.pb -rpx I2C_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force I2C_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  catch { write_mem_info -force I2C.mmi }
  write_bitstream -force I2C.bit 
  catch {write_debug_probes -quiet -force I2C}
  catch {file copy -force I2C.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

