#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Feb 01 10:25:43 IST 2026
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim master1_sim_behav -key {Behavioral:sim_1:Functional:master1_sim} -tclbatch master1_sim.tcl -view /home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/start_state_success.wcfg -log simulate.log"
xsim master1_sim_behav -key {Behavioral:sim_1:Functional:master1_sim} -tclbatch master1_sim.tcl -view /home/krushna_dev/all_verilog_codes/vivado/I2C interface/i2c_v2019/start_state_success.wcfg -log simulate.log

